// SPDX-License-Identifier: GPL-3.0-or-later
//
// +-------------------------------------------------------------------------+
// |         3PID INVITE CONFORMANCE TEST (IS-BACKED POSITIVE PATH)          |
// |                                                                         |
// |  Spec: Matrix Client-Server API v1.19 — Third-party invites             |
// |  URL:  ../../docs/matrix-v1.19-spec/client-server-api.md#third-party-invites |
// |                                                                         |
// |  Proves the positive path that the existing negative conformance test   |
// |  (test_client_server_conformance.cpp:8432) explicitly defers: when an   |
// |  operator-trusted identity server is reachable, POST /rooms/{roomId}/  |
// |  invite with id_server/medium/address drives a real IS /store-invite   |
// |  round trip and persists an m.room.third_party_invite whose state_key  |
// |  is the IS-issued token (not a locally-fabricated one). The mock IS    |
// |  runs on a real local TLS socket via the test_forced_identity_resolution |
// |  seam — no production discovery path is weakened.                      |
// +-------------------------------------------------------------------------+

#include "../support/json_test_support.hpp"
#include "../support/registration_token.hpp"
#include "../support/tls_mock_server.hpp"
#include "merovingian/config/config.hpp"
#include "merovingian/database/persistent_store.hpp"
#include "merovingian/homeserver/client_server.hpp"
#include "merovingian/homeserver/local_http_router.hpp"
#include "merovingian/identity/identity_client.hpp"
#include "merovingian/net/tcp_acceptor.hpp"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <filesystem>
#include <string>
#include <thread>

namespace
{

using namespace merovingian::tests;

[[nodiscard]] auto conformance_config() -> merovingian::config::Config
{
    auto security = merovingian::config::SecurityConfig{};
    merovingian::tests::enable_token_registration(security);
    return {
        merovingian::config::ServerConfig{},           merovingian::config::ListenersConfig{},
        merovingian::config::DatabaseConfig{},         security,
        merovingian::config::ClientRateLimitsConfig{}, merovingian::config::LogModulesConfig{},
    };
}

// Registers alice and logs her in, returning the access token.
[[nodiscard]] auto logged_in_token(merovingian::homeserver::ClientServerRuntime& runtime) -> std::string
{
    auto const reg = merovingian::homeserver::handle_client_server_request(
        runtime,
        {"POST", "/_matrix/client/v3/register", {}, merovingian::tests::registration_json("alice", "CorrectHorse7!")});
    REQUIRE(reg.response.status == 200U);
    auto const login = merovingian::homeserver::handle_client_server_request(
        runtime,
        {"POST",
         "/_matrix/client/v3/login",
         {},
         R"({"type":"m.login.password","identifier":{"type":"m.id.user","user":"@alice:example.org"},"password":"CorrectHorse7!","device_id":"DEVICE1"})"});
    REQUIRE(login.response.status == 200U);
    auto const login_body = parse_object(login.response.body);
    auto const* token = string_member(login_body, "access_token");
    REQUIRE(token != nullptr);
    REQUIRE(!token->empty());
    return *token;
}

// Creates a room for the logged-in user and returns the room_id.
[[nodiscard]] auto create_room(merovingian::homeserver::ClientServerRuntime& runtime,
                               std::string const& token) -> std::string
{
    auto const r = merovingian::homeserver::handle_client_server_request(
        runtime, {"POST", "/_matrix/client/v3/createRoom", token, "{}"});
    REQUIRE(r.response.status == 200U);
    auto const body = parse_object(r.response.body);
    auto const* rid = string_member(body, "room_id");
    REQUIRE(rid != nullptr);
    return *rid;
}

} // namespace

// Spec: Matrix Client-Server API v1.19 — Third-party invites
// URL:  ../../docs/matrix-v1.19-spec/client-server-api.md#third-party-invites
//
// Spec MUST (client-server-api.md § Third-party invites): when the identity
// server does not know a Matrix ID for the 3PID, "the identity server
// generating a token, which it gives to the inviting homeserver. The
// homeserver will add an m.room.third_party_invite event into the graph for
// the room, containing that token."
// Spec MUST (SignedThirdPartyInvite): the token "generated by the identity
// server at the /store_invite endpoint ... matches the state_key of the
// corresponding m.room.third_party_invite event."
SCENARIO("POST /rooms/{roomId}/invite with a trusted id_server issues an IS-backed m.room.third_party_invite",
         "[conformance][client-server][room-membership][3pid]")
{
    GIVEN("a room owned by alice and a trusted mock identity server")
    {
        auto started = merovingian::homeserver::start_client_server(conformance_config());
        REQUIRE(started.started);

        auto const alice = logged_in_token(started.runtime);
        auto const room_id = create_room(started.runtime, alice);

        auto const is_host = std::string{"is.localhost.test"};

        // Stand up a mock IS on a real local TLS socket. The seam keys off the
        // IS host and overrides the resolved address to 127.0.0.1, so the URL
        // the HS builds must carry the same port the mock listens on. The
        // certificate CN must be the IS host, not "localhost": the HS verifies
        // the peer name against the URL host, and a mismatch fails the handshake.
        auto cert = merovingian::tests::tls_mock::write_test_tls_certificate(is_host);
        auto tls_ctx = merovingian::homeserver::make_tls_server_context(cert.certificate_file, cert.private_key_file);
        REQUIRE(tls_ctx.ok());
        auto acceptor = merovingian::net::TcpAcceptor{};
        REQUIRE(acceptor.bind("127.0.0.1", 0U).ok);
        auto const port = acceptor.bound_port();
        REQUIRE(port > 0U);

        auto const is_host_port = is_host + ":" + std::to_string(port);
        auto const is_base_url = std::string{"https://"} + is_host_port;

        // Configure the runtime's identity-server trust BEFORE dispatching.
        // The matcher (room_service.cpp::invite_user_by_threepid) parses each
        // trusted_servers entry as an https URL and matches host+port against
        // the client's id_server (also host:port). default_server is the
        // fallback when a client omits id_server; set it for completeness.
        started.runtime.homeserver.config.server().identity_server.default_server = is_base_url;
        started.runtime.homeserver.config.server().identity_server.trusted_servers = {is_base_url};

        // Test-only seam: pin the IS host to the loopback address and trust the
        // self-signed cert via an in-memory CA bundle. No production path sets
        // this; the HS's SSRF-safe discovery is bypassed for this host only.
        started.runtime.homeserver.test_forced_identity_resolution[is_host] =
            merovingian::identity::TestForcedIdentityResolution{{"127.0.0.1"}, cert.certificate_pem};

        // Canned store-invite 200 response. The IS — not the HS — generates the
        // token, display_name, and public_keys (long-term + ephemeral).
        auto const store_invite_body = std::string{
            R"({"token":"is-issued-token-123","display_name":"bob","public_keys":[)"
            R"({"public_key":"longterm-pk-base64","key_validity_url":"https://is.localhost.test/kv/lt"},)"
            R"({"public_key":"ephemeral-pk-base64","key_validity_url":"https://is.localhost.test/kv/eph"}]})"};
        auto const store_invite_response =
            merovingian::tests::tls_mock::json_http_response("200 OK", store_invite_body);

        auto server_thread = std::thread{[&] {
            merovingian::tests::tls_mock::run_one_shot_tls_server(acceptor, *tls_ctx.context, store_invite_response);
        }};
        auto const server_join = merovingian::tests::tls_mock::ScopedThreadJoin{server_thread};

        WHEN("alice invites a third-party email via the trusted IS")
        {
            auto const invite_body =
                std::string{R"({"id_server":")"} + is_host_port +
                R"(","medium":"email","address":"bob@example.org","id_access_token":"opaque-access-token"})";
            auto const invite = merovingian::homeserver::handle_client_server_request(
                started.runtime, {"POST", "/_matrix/client/v3/rooms/" + room_id + "/invite", alice, invite_body});

            server_thread.join();

            THEN("200 + m.room.third_party_invite persisted with the IS-issued token as state_key")
            {
                // Spec MUST: the HS forwards the 3PID to the trusted IS and emits
                // the m.room.third_party_invite only after the IS issues the token.
                REQUIRE(invite.response.status == 200U);

                auto const& store = started.runtime.homeserver.database.persistent_store;
                auto const tpi_state =
                    std::ranges::find_if(store.state, [&room_id](merovingian::database::PersistentStateEvent const& s) {
                        return s.room_id == room_id && s.event_type == "m.room.third_party_invite";
                    });
                REQUIRE(tpi_state != store.state.end());
                // Spec MUST: the token is generated by the IS at /store-invite and
                // matches the event state_key.
                REQUIRE(tpi_state->state_key == "is-issued-token-123");
            }
        }
    }
}
