#!/usr/bin/env python3
from __future__ import annotations

import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
WORKFLOW = REPO_ROOT / ".github" / "workflows" / "release.yml"


class ReleaseWorkflowTests(unittest.TestCase):
    def test_alpha_tags_trigger_release_publication(self) -> None:
        # GIVEN the repository release workflow.
        self.assertTrue(WORKFLOW.is_file(), "release workflow is missing")
        workflow = WORKFLOW.read_text(encoding="utf-8")

        # WHEN alpha tags are pushed.
        # THEN the workflow triggers on the alpha tag pattern.
        self.assertIn("tags:", workflow)
        self.assertIn("- 'v*-alpha*'", workflow)

    def test_hardened_linux_and_freebsd_packages_are_built(self) -> None:
        # GIVEN the repository release workflow.
        self.assertTrue(WORKFLOW.is_file(), "release workflow is missing")
        workflow = WORKFLOW.read_text(encoding="utf-8")

        # WHEN alpha assets are built.
        # THEN both supported package jobs use the hardened profile.
        self.assertIn(
            "sh scripts/build-linux.sh --builddir build-linux-release --profile hardened",
            workflow,
        )
        self.assertIn(
            "sh scripts/build-bsd.sh --builddir build-freebsd-release --profile hardened",
            workflow,
        )
        self.assertIn("sh scripts/check-release-readiness.sh", workflow)

    def test_alpha_packages_include_system_package_scaffolds(self) -> None:
        # GIVEN the repository release workflow.
        self.assertTrue(WORKFLOW.is_file(), "release workflow is missing")
        workflow = WORKFLOW.read_text(encoding="utf-8")

        # WHEN alpha assets are staged.
        # THEN Debian, RPM, and BSD package scaffolds are copied into the release tarballs.
        self.assertIn("packaging/deb", workflow)
        self.assertIn("packaging/rpm", workflow)
        self.assertIn("packaging/freebsd", workflow)
        self.assertIn("packaging/openbsd", workflow)
        self.assertIn("packaging/netbsd", workflow)
        self.assertIn("libsodium-dev", workflow)
        self.assertIn("libpq-dev", workflow)
        self.assertIn("libsodium postgresql17-client", workflow)

    def test_alpha_release_publishes_prerelease_assets_and_checksums(self) -> None:
        # GIVEN the repository release workflow.
        self.assertTrue(WORKFLOW.is_file(), "release workflow is missing")
        workflow = WORKFLOW.read_text(encoding="utf-8")

        # WHEN alpha packages are published.
        # THEN the workflow generates checksums and uploads a GitHub prerelease.
        self.assertIn("sha256sum", workflow)
        self.assertIn("sha256 -q", workflow)
        self.assertIn("softprops/action-gh-release@v2", workflow)
        self.assertIn("prerelease: true", workflow)

    def test_alpha_release_attaches_slsa_provenance_attestation(self) -> None:
        # GIVEN the repository release workflow.
        self.assertTrue(WORKFLOW.is_file(), "release workflow is missing")
        workflow = WORKFLOW.read_text(encoding="utf-8")

        # WHEN alpha packages are published.
        # THEN each artifact carries a SLSA provenance attestation generated by
        # actions/attest-build-provenance and verifiable with `gh attestation verify`.
        # The job must also declare the `attestations: write` permission that the
        # action requires to publish to the repository attestation store.
        self.assertIn("attest-build-provenance", workflow)
        self.assertIn("attestations: write", workflow)
        self.assertIn("id-token: write", workflow)

    def test_release_notes_record_compiler_dependency_and_test_evidence(self) -> None:
        # GIVEN the repository release workflow.
        self.assertTrue(WORKFLOW.is_file(), "release workflow is missing")
        workflow = WORKFLOW.read_text(encoding="utf-8")

        # WHEN a release is published.
        # THEN each hardened platform build collects release evidence (compiler
        # version, link-time hardening confirmation, pinned dependency
        # versions, test log summary, fuzz target names) via the shared
        # scripts/collect-release-evidence.sh helper, uploads it as its own
        # artifact, and the publish job downloads and folds every platform's
        # evidence into the published release notes alongside the package
        # checksums — closing production-milestone.md's "Record compiler
        # version, linker flags, dependency versions, test logs, sanitizer
        # logs, fuzz target names, package checksums, and GPG signatures in
        # release notes" bullet.
        self.assertIn("scripts/collect-release-evidence.sh", workflow)
        self.assertIn("release-evidence-linux-", workflow)
        self.assertIn("release-evidence-freebsd-", workflow)
        self.assertIn("## Package checksums", workflow)
        self.assertIn("## Release evidence", workflow)


if __name__ == "__main__":
    unittest.main()
