#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

# PROVIDE: merovingian
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="merovingian"
rcvar="merovingian_enable"
command="/usr/local/bin/merovingian-server"
command_args="--config ${merovingian_config:-/usr/local/etc/merovingian/merovingian.conf}"
merovingian_user="${merovingian_user:-merovingian}"
pidfile="/var/run/merovingian/merovingian.pid"

start_precmd="merovingian_precmd"

merovingian_precmd() {
    install -d -o "${merovingian_user}" -g "${merovingian_user}" -m 0750 /var/run/merovingian
    install -d -o "${merovingian_user}" -g "${merovingian_user}" -m 0750 /var/db/merovingian
    install -d -o "${merovingian_user}" -g "${merovingian_user}" -m 0750 /var/log/merovingian
}

load_rc_config "$name"
: "${merovingian_enable:=NO}"
run_rc_command "$1"
