name: bsd-build

on:
  push:
  pull_request:

jobs:
  freebsd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          run: |
            pkg install -y meson ninja llvm catch2 pkgconf git
            meson setup build -Dbuild_tests=true -Dbuild_fuzz=false
            meson compile -C build
            meson test -C build --print-errorlogs
